language: node_js
node_js:
  - '11'

script:
  - yarn test
  - yarn lint

before_deploy:
  - yarn build
deploy:
  - provider: pages
    skip-cleanup: true
    keep-history: true
    target-branch: gh-pages
    github-token:
      secure: 'IIEJqJFcknstORwOMXI6JWs8KVULY0QHSA+XzTQ09Jhbs0o5gnIZZOPk7b959sbrTPWOY+/+pfesl/pnJs9KAwgvaWt895zVWR2WuozCoznkYQGCLkVqIAljsC5kcG+0rQVlp91uLLNNQus6Hb0Iq3gc25yEHXFBegJB8cNz/AkuZIFmrbwShSWH9O/JO/4xyfON9V2Id2i9dKy6K7uPfwhzun51EOb20AWGgTC2mdNTuaCC1tr63VsM2rYF6nFV+Y2HOmyOdl4VHBopTVd5FB8hP3Uzw1i8gNZ3IN7xqzieterKgoGkwsVSP1cEIZH4GkCxComG81R0nk4AfF0rZSI+D/XSBcc46XhRe5QmyEfKWPvWk1EaCry/+AdTwez0gYKHDgxJOGoEq47Gtil+7RqOl6RqplShKIeBRt6JMPDijf4USsefDzu1JLjmB5dvsvZ3qm07IQES6dUqFmerK3+GGyoXRs0z50LC5dDuBOtrrc6HnAqOLAUh/4k46fXc2Y25+kXkbvhWYry/oM0u7WuGUltchQwG7yuqVDzLkaIZgBGS/Nny1g23iZU9veVcDZgp7FF2esIxnAkpgQo4C11aCRcpVty/7uidypuEX4heSG6PRtU5QdE5BUTJBP0zSqdpoj5QdKrpYquSOYc5k5u0mPUFi2g+iYOCilkAe+w='
    local-dir: docs
    name: TSUYUSATO Kitsune (bot)
    email: make.just.on@gmail.com
    on:
      branch: master
  - provider: npm
    email: make.just.on@gmail.com
    skip_cleanup: true
    api_key:
      secure: EPTebYuKDZSVrjOgEF/vccu82OvW/snCS9ghALJQciwD2FNJgPQ4YrQHwPF6PTIeLAsYSOp4j2tYxG+G8/1No54sqHI2bU6SpS96JaSCaHH7Ah6Rk0Ul2Rujs+t+eqCZH0sX+h2NARivcDMTJtviJQNe+7ceOPLjnF7j6RCEi98l8ufyetP6qi51Oal+GXGyL48kgQNvys+XjccjhinNKZbNrDkqoOHxd7jhhUrCqhs1ASDzJX02WI+oH9t3o8eKs75Vfcg78YMizoambQElF7FnNP8jaraoDy3N9CwJQf7sOxwGRyS5VPydFTF51SX0qs9CY7p4YL7kyJ3iGmy8uhnQz7XVFjg+APjVJexWIkkZMQfcEh13PAGvMQ6Q1m4kFPFQKE0XlW+mlp2GGa5+fEh9SOICx8t38L2yj3cxzJO5zxyjU2qd4os1WUJC8QmuFkUdZiIEWSQWJIxwifzB/OvLcYStd5wC6Jb+dtuFeMyTYnCjA0aEd1rqWy3Qs0XWIZkoMmPPC0UqxjigM9PBKfMfY0tylzUasWZsmKio/SK3VZ8L6HM23pdhS1bVMIiJ9AqIDiuB4YyE2u0ox7ZgKrtRnxYq4kLet1OnbmyMftC/3hTbQGX1KJh7M00QqOe8iTgYNJed4N/PETdjyWDasSMgd5it2hN2TvuvAKgC4tI=
    on:
      tags: true
      repo: MakeNowJust/md.html
